### ISSUE TITLE
OutOfMemoryError thrown when testing Netty on Travis CI

### ISSUE THREAD

**Issue by flowersinthesand** [cettia/asity#1]
On my desktop where Windows 8.1 64 bit and Java 7u55 are installed and Windows 10 64 bit and Java 7u71, it has never happened so I'm not sure how I should approach the issue.

Here is log:
- https://travis-ci.org/vibe-project/vibe-java-platform/builds/40855806#3327
- https://travis-ci.org/vibe-project/vibe-java-platform/builds/41443031#3160
- https://travis-ci.org/vibe-project/vibe-java-platform/builds/41859152#3173
- https://travis-ci.org/vibe-project/vibe-java-platform/builds/41941084#3550
- https://travis-ci.org/vibe-project/vibe-java-platform/builds/47325761#3541
- https://travis-ci.org/cettia/asity/jobs/74794604#L3023
- https://travis-ci.org/cettia/asity/jobs/74794603#L3023
- https://travis-ci.org/cettia/asity/jobs/74797771#L3023
- https://travis-ci.org/cettia/asity/jobs/74797768#L3023

The error's typical stack trace looks like:

```
13:27:55.475 WARN [Time-limited test] i.n.c.AbstractChannel [Slf4JLogger.java:146] Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x93ff02c4]
java.lang.OutOfMemoryError: unable to create new native thread
    at java.lang.Thread.start0(Native Method) [na:1.7.0_76]
    at java.lang.Thread.start(Thread.java:714) [na:1.7.0_76]
    at io.netty.util.concurrent.SingleThreadEventExecutor.startThread(SingleThreadEventExecutor.java:853) ~[netty-common-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:727) ~[netty-common-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:420) ~[netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:48) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:64) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:317) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:273) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:269) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:244) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.cettia.platform.bridge.netty4.NettyServerWebSocketTest.startServer(NettyServerWebSocketTest.java:76) [test-classes/:na]
    at io.cettia.platform.test.ServerWebSocketTest.before(ServerWebSocketTest.java:58) [classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_76]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_76]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_76]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_76]
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) [junit-4.12.jar:4.12]
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.12.jar:4.12]
    at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298) [junit-4.12.jar:4.12]
    at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292) [junit-4.12.jar:4.12]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_76]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_76]
```

**Comment by flowersinthesand** [comment]
I'm not sure but it seems that 2cb6d9c3819e814b1beecbebf7619a595e3e4847 mitigates this issue.

**Comment by flowersinthesand** [comment]
https://github.com/cettia/asity/commit/4f0681c33a4b7a519b5c4728446fea2440e86624 seems to fix this issue - https://travis-ci.org/cettia/asity/builds/334046999

I'm going to close this.
